[package]
name = "sundile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# general
winit = "*"
legion = "*"
futures = "*"

# debug_gui
egui = "0.16"
egui_wgpu_backend = "0.16"
egui_winit_platform = "0.13"
epi = "0.16"

# internal
sundile_core = { path = "../core" }
sundile_graphics = { path = "../graphics" }
sundile_assets = { path = "../assets" }
sundile_scripting = { path = "../scripting" }