[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[[example]]
name="basic"

[dependencies]
# local crates
sundile = {path="../engine/"}

# workspace deps
wgpu = {workspace = true}
winit = {workspace = true}
