[package]
name = "sundile_assets"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
thiserror = "*"
bincode = "*"
serde = {version = "*", features = ["derive"]}
tobj = "*"
cgmath = "*"
wgpu = "*"
bytemuck = "*"
naga = "*"

sundile_graphics = { path = "../graphics/" }

[dev-dependencies]
winit = "*"
futures = "*"